# SPDX-License-Identifier: GPL-2.0

CFLAGS_trace.o := -I$(src)

obj-y := p4tc_types.o p4tc_pipeline.o p4tc_tmpl_api.o \
	p4tc_parser_api.o p4tc_hdrfield.o p4tc_action.o p4tc_table.o \
	p4tc_tbl_entry.o p4tc_runtime_api.o p4tc_bpf.o trace.o p4tc_ext.o \
	p4tc_tmpl_ext.o
