# SPDX-License-Identifier: GPL-2.0

CFLAGS_trace.o := -I$(src)

obj-y := p4tc_types.o p4tc_pipeline.o p4tc_tmpl_api.o p4tc_meta.o \
	p4tc_parser_api.o p4tc_hdrfield.o p4tc_action.o p4tc_table.o \
	p4tc_tbl_api.o p4tc_register.o p4tc_cmds.o trace.o
