/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __NET_P4TC_EXT_METER_H
#define __NET_P4TC_EXT_METER_H

#define P4TC_EXTERN_METER_ID 0x1B000000
#define P4TC_EXTERN_DIRECT_METER_ID 0x1C000000

#define P4TC_EXTERN_METER_COLOR_UNSPEC -1

enum meter_colors {
	P4TC_EXTERN_METER_COLOR_RED,
	P4TC_EXTERN_METER_COLOR_GREEN,
	P4TC_EXTERN_METER_COLOR_YELLOW,
};

#endif /* __NET_P4TC_EXT_METER_H */
