name: Build each commit incrementally (32-bit)

on:
  push:
    branches-ignore:
       - 'master**'
  workflow_dispatch:

jobs:
  build-gcc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          sudo apt update && sudo apt install -y gawk flex bison openssl libssl-dev libelf-dev libudev-dev libpci-dev libiberty-dev
          make tinyconfig
          ./scripts/config --enable NET
          ./scripts/config --enable NET_INGRESS
          ./scripts/config --enable NET_EGRESS
          ./scripts/config --enable INET
          ./scripts/config --enable NET_SCHED
          ./scripts/config --enable NET_CLS
          ./scripts/config --enable NET_CLS_ACT
          ./scripts/config --enable NET_TC_SKB_EXT
          ./scripts/config --enable NET_ACT_METACT
          ./scripts/config --enable NET_CLS_P4
          ./scripts/config --enable KSM
          ./scripts/config --enable KPARSER
          make listnewconfig >> .config
          for commit in $(git rev-list origin/master-6.1..HEAD); do
              git checkout $commit
              ./scripts/config --enable NET_P4_TC
              make -j $(nproc)
          done

  build-clang:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          sudo apt update && sudo apt install -y gawk flex bison openssl libssl-dev libelf-dev libudev-dev libpci-dev libiberty-dev
          make CC=clang tinyconfig
          ./scripts/config --enable NET
          ./scripts/config --enable NET_INGRESS
          ./scripts/config --enable NET_EGRESS
          ./scripts/config --enable INET
          ./scripts/config --enable NET_SCHED
          ./scripts/config --enable NET_CLS
          ./scripts/config --enable NET_CLS_ACT
          ./scripts/config --enable NET_TC_SKB_EXT
          ./scripts/config --enable NET_ACT_METACT
          ./scripts/config --enable NET_CLS_P4
          ./scripts/config --enable KSM
          ./scripts/config --enable KPARSER
          make CC=clang listnewconfig >> .config
          for commit in $(git rev-list origin/master-6.1..HEAD); do
              git checkout $commit
              ./scripts/config --enable NET_P4_TC
              make CC=clang -j $(nproc)
          done
