name: Run checkpatch.pl

on:
  push:
    branches-ignore:
       - 'master**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          sudo apt update && sudo apt install -y python3-pip codespell
          pip install ply
          pip install gitpython
          ./scripts/checkpatch.pl --codespell --git origin/master..HEAD
