name: Run sparse

on:
  push:
    branches-ignore:
       - 'master**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          sudo apt update && sudo apt install -y gawk flex bison openssl libssl-dev libelf-dev libudev-dev libpci-dev libiberty-dev sparse
          make tinyconfig
          ./scripts/config --enable NET
          ./scripts/config --enable NET_INGRESS
          ./scripts/config --enable NET_EGRESS
          ./scripts/config --enable INET
          ./scripts/config --enable NET_SCHED
          ./scripts/config --enable NET_CLS
          ./scripts/config --enable NET_CLS_ACT
          ./scripts/config --enable NET_TC_SKB_EXT
          ./scripts/config --enable NET_P4_TC
          make listnewconfig >> .config
          make C=2 net/
